server:
  port: 8080

spring:
  application:
    name: Graph
  sleuth:
    sampler:
      probability: 1
  datasource:
    initialization-mode: never
    hikari:
      pool-name: h2
      jdbc-url: jdbc:h2:mem:test-${random.int};DB_CLOSE_DELAY=-1
      username: sa
      password:
      maximum-pool-size: 10
  zipkin:
    message-timeout: 1
  profiles:
    active: 'dev'

  main:
    allow-bean-definition-overriding: true

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    subscriptions:
      websocket:
        path: /subscriptions
    actuator-metrics: true
    exception-handlers-enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus

logging:
  level:
    Exposed: DEBUG

